apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: insolar
  name: nginx-deployment
  labels:
    app: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          ports:
            - containerPort: 80
          image: docker.io/f4hrenh9it/insolar_nginx_test:1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: insolar
  name: nginx-test-service
spec:
  type: NodePort
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80