name: ve-performance check
on:
  pull_request:
  schedule:
    - cron: '0 1 * * *'
env:
  KUBECONFIG: "${{ github.workspace }}/aks.yaml"
  GO_VERSION: 1.14
  GOPATH: /home/runner/work/
  GOPROXY: https://proxy.golang.org,https://goproxy.io,direct
  ACR_HOST: usciregistry.azurecr.io
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assured-ledger
        uses: actions/checkout@v2
        with:
          path: ./assured-ledger
          repository: insolar/assured-ledger
      - name: Build docker images
        run: |
          cd assured-ledger/ledger-core
          make docker-build
      - name: Push assured ledger image to Azure container registry registry
        run: |
          docker login $ACR_HOST --username ${{secrets.ACR_SP_ID}} --password ${{secrets.ACR_SP_SECRET}}
          docker tag insolar/assured-ledger:latest $ACR_HOST/assured-ledger:${GITHUB_SHA:0:8}
          docker push $ACR_HOST/assured-ledger:${GITHUB_SHA:0:8}
  ve-perf-test:
    name: ve-perf-test
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aks-10node, aks-15node, aks-20node]
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: Checkout assured-ledger
        uses: actions/checkout@v2
        with:
          ref: OPS-281-aks
          path: ./assured-ledger
          repository: insolar/assured-ledger
      - name: Preparation - set prerequisite variables, full sha is ${{github.sha}}
        env:
          TARGET: ${{matrix.target}}
        run: |
          echo "::set-env name=INSOLAR_TAG::${GITHUB_SHA:0:8}"
          echo "::set-env name=INSOLAR_NETWORK_SIZE::${TARGET}"
          echo "::set-env name=INSOLAR_NAMESPACE::${GITHUB_SHA:0:8}-${TARGET}"
          echo "::set-env name=INSOLAR_DESIRED_UPTIME::300"
      - name: Preparation - copy docker auth secret
        run: |
          docker login $ACR_HOST --username ${{secrets.ACR_SP_ID}} --password ${{secrets.ACR_SP_SECRET}}
          cp /home/runner/.docker/config.json assured-ledger/ledger-core/scripts/deploy/kube/gitops/"$INSOLAR_NETWORK_SIZE"/dockerconfigjson
      - name: Preparation - save kubeconfig
        run: echo "${{secrets.CLOUD_KUBECONFIG}}" >> aks.yaml
      - name: Praparation - github token for gitops access
        run: git config --global url."https://${{secrets.INS_SERVICE_PAT}}@github.com/".insteadOf "https://github.com/"
      - name: Ingress access check (IF THIS STEP FAILED - CALL DEVOPS, RED ALERT)
        run:  curl -s "https://$PROMETHEUS_USER:$PROMETHEUS_PASS@prometheus.uscifarm.insolar.io/prometheus/api/v1/labels" | jq -r '.status'
      - name: Deploy network
        run: kubectl kustomize assured-ledger/ledger-core/scripts/deploy/kube/gitops/"$INSOLAR_NETWORK_SIZE" | envsubst '${INSOLAR_NAMESPACE} ${INSOLAR_TAG}' | kubectl -n $INSOLAR_NAMESPACE apply -f -
      - name: Rollout check (IF THIS STEP FAILED - CALL DEV/OPS, YELLOW ALERT)
        run: kubectl -n $INSOLAR_NAMESPACE rollout status sts/virtual --timeout=300s
      - name: Provide link to grafana
        run:  echo "https://monitoring.uscifarm.insolar.io/d/LmD-fXFZz/ins-network?orgId=1&refresh=10s&var-phase=All&var-packetType=All&var-namespace=$INSOLAR_NAMESPACE&from=now-10m&to=now"
      - name: Set network start time variable
        run:  echo "::set-env name=INSOLAR_START_TIME::$(date +'%s')"
      - name: wait until uscifarm.insolar.io is ready
        run: |
          echo 'Sadly we dont know a better way than:'
          sleep 30
      - name: start test
        run: |
          TARGET=http://${INSOLAR_NAMESPACE}.uscifarm.insolar.io REPORT_CSV_FILE=scaling.csv WALLETS=100 NODES=$(echo $INSOLAR_NETWORK_SIZE | awk '{gsub(/[^[0-9]]*/,"");print}') go run cmd/test/main.go
          cat scaling.csv
      - name: aggregate logs
        if: always()
        run: |
          mkdir -p logs/${INSOLAR_NAMESPACE}
          kubectl -n ${INSOLAR_NAMESPACE} logs --since=12h pulsar-0 > logs/${INSOLAR_NAMESPACE}/pulsar-0.log
          for pod in $(kubectl -n $INSOLAR_NAMESPACE get po -lapp=virtual -o=custom-columns=NAME:.metadata.name --no-headers); do
            kubectl -n ${INSOLAR_NAMESPACE} logs --since=12h $pod > logs/${INSOLAR_NAMESPACE}/$pod.log
          done
      - name: cleanup
        if: always()
        run: kubectl delete ns ${INSOLAR_NAMESPACE} --ignore-not-found=true
