name: nginx-test
on:
  pull_request:
  schedule:
    - cron: '0 1 * * *'
env:
  KUBECONFIG: "${{ github.workspace }}/aks.yaml"
  GO_VERSION: 1.14
  GOPATH: /home/runner/work/
  GOPROXY: https://proxy.golang.org,https://goproxy.io,direct
  ACR_HOST: usciregistry.azurecr.io
  PROMETHEUS_USER: ${{secrets.PROMETHEUS_USER}}
  PROMETHEUS_PASS: ${{secrets.PROMETHEUS_PASS}}
jobs:
  nginx-test:
    name: nginx-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: Preparation - save kubeconfig
        run: echo "${{secrets.CLOUD_KUBECONFIG}}" >> aks.yaml
      - name: Preparation - set prerequisite variables, full sha is ${{github.sha}}
        run: |
          echo "::set-env name=INSOLAR_TAG::${GITHUB_SHA:0:8}"
          echo "::set-env name=INSOLAR_NETWORK_SIZE::${TARGET}"
          echo "::set-env name=INSOLAR_NAMESPACE::insolar-nginx-test"
          echo "::set-env name=INSOLAR_DESIRED_UPTIME::300"
      - name: Praparation - github token for gitops access
        run: git config --global url."https://${{secrets.INS_SERVICE_PAT}}@github.com/".insteadOf "https://github.com/"
      - name: Ingress access check (IF THIS STEP FAILED - CALL DEVOPS, RED ALERT)
        run:  curl -s "https://$PROMETHEUS_USER:$PROMETHEUS_PASS@prometheus.uscifarm.insolar.io/prometheus/api/v1/labels" | jq -r '.status'
      - name: Deploy network
        run: |
          kubectl -n $INSOLAR_NAMESPACE apply -f deploy/kube/nginx_test/deployment.yaml
      - name: wait nginx is ready
        run: |
          sleep 20
      - name: Rollout check (IF THIS STEP FAILED - CALL DEV/OPS, YELLOW ALERT)
        run: kubectl -n $INSOLAR_NAMESPACE rollout status sts/virtual --timeout=10m
      - name: Provide link to grafana
        run:  echo "https://monitoring.uscifarm.insolar.io/d/LmD-fXFZz/ins-network?orgId=1&refresh=10s&var-phase=All&var-packetType=All&var-namespace=$INSOLAR_NAMESPACE&from=now-10m&to=now"
      - name: Set network start time variable
        run:  echo "::set-env name=INSOLAR_START_TIME::$(date +'%s')"
      - name: wait until uscifarm.insolar.io is ready
        run: |
          echo 'Sadly we dont know a better way than:'
          sleep 60
      - name: start test
        run: |
          TARGET=http://${INSOLAR_NAMESPACE}.uscifarm.insolar.io:32081 go run cmd/nginx_test/main.go
      - name: cleanup
        if: always()
        run: |
          kubectl -n $INSOLAR_NAMESPACE delete deployments nginx-deployment
